"""empty message

Revision ID: 521fe7716703
Revises: 24702bb937ca
Create Date: 2020-03-16 22:49:25.881312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521fe7716703'
down_revision = '24702bb937ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=True))
    
    op.execute('UPDATE todo SET completed = False WHERE completed IS NULL')
    op.alter_column('todo', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
